services:
  users-service:
    container_name: users-service
    build:
      context: ./users
      dockerfile: ./Dockerfile
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - users-service